version: '3'

services:
  client:
    build: ./client/
    ports:
      - "8081:8081"

  server:
    build: ./server/
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    environment:
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      STEAM_API_KEY: ${STEAM_API_KEY}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      URL_MONGO: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017"

  mongo:
    image: mongo:4.0
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}